### ISSUE TITLE
Cannot Install On WSL Ubuntu 24.04.1

### ISSUE THREAD

**Issue by GaoHengSiang** [htm-community/htm.core#1028]
Hello,
  I am attempting to install htm.core on Windows Subsystem for Linux (WSL), which is running Ubuntu 24.04.1 (the python version is 3.12.3). Here is what I've done:
First, I ran these commands:
`sudo apt update`
`sudo apt upgrade`
then I installed virtualenv and python3.12.4 from source. The rest of the commands are:
`virtualenv htm_venv --python=python3.12.4`
`source htm_venv/bin/activate`
`git clone https://github.com/htm-community/htm.core`
`python -m ensurepip --upgrade`
`python -m pip install setuptools packaging`
`cd htm.core/`

I edited line 7 of requirements.txt, changing
`numpy==1.23 ` to `numpy ~= 1.26.4 `
Finally:
`pip install -r requirements.txt`
`python setup.py install`
The installation failed with this error: 
`~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[1]: *** [CMakeFiles/Makefile2:179: src/CMakeFiles/LibrarySource.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
Traceback (most recent call last):
  File "/home/hansgao/project/htm.core/setup.py", line 414, in <module>
    getExtensionFiles(platform, build_type)
  File "/home/hansgao/project/htm.core/setup.py", line 239, in getExtensionFiles
    generateExtensions(platform, build_type)
  File "/home/hansgao/project/htm.core/setup.py", line 305, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type, "--", "-j", "4"])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.`

I tried to install with python3.12.3 too, and the "-dev" versions of python were installed in both cases, but the same error persists
Please let me know if you require more information!

**Comment by fcr** [comment]
htm.core doesn't support Python 3.12 yet.

**Comment by dkeeney** [comment]
I am traveling and I will not be able to work on this until mid Nov.  If anyone else wants to take a crack at this it would be appreciated.  See issue #1024 and #1025

**Comment by heckop** [comment]
@fcr Please help me with this issue:
<img width="1102" alt="Screenshot 2024-10-20 at 6 36 45 PM" src="https://github.com/user-attachments/assets/d6974ff8-a6ec-4b70-bf6b-36b8405541b5">

dependencies of htm.core is not available on pypi

**Comment by fcr** [comment]
@heckop as mentioned above, Python 3.12 is not yet supported by htm.core. You have Python 3.12 installed!
