### ISSUE TITLE
setup.py install cryptic error when cmake is missing

### ISSUE THREAD

**Issue by bhargav-95** [htm-community/htm.core#436]
Traceback (most recent call last):
  File "setup.py", line 57, in <module>

  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\I0000847\Documents\Time series Anomaly detection packages\nupic
.cpp-master\bindings\py\packaging\setup.py", line 226, in <module>
    getExtensionFiles(platform)
  File "C:\Users\I0000847\Documents\Time series Anomaly detection packages\nupic
.cpp-master\bindings\py\packaging\setup.py", line 182, in getExtensionFiles
    generateExtensions()
  File "C:\Users\I0000847\Documents\Time series Anomaly detection packages\nupic
.cpp-master\bindings\py\packaging\setup.py", line 211, in generateExtensions
    subprocess.check_call(["cmake", PY_VER, REPO_DIR])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 990, in _execute_child

    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by bhargav-95** [comment]
python setup.py install --user --force

# This is how i try to install (pretty basic) from the root directory of the folder

**Comment by dkeeney** [comment]
We don't currently support Anaconda although other people in the blog have been able to get it to work.

**Comment by breznak** [comment]
Thank you both for looking into this! 
We don't currently have resources and motivation to support Anaconda python builds (this is documented in the Readme), so I'm marking this as won't fix. 
On the other hand, if @bhargav-95 or someone can put a PR with the support, I'll be open to merging that.

**Comment by bhargav-95** [comment]
Hello,

I'm sorry the title is misleading.
I'm trying to do a pip install .
This is not on anaconda .
It is for Python 3.7

**Comment by breznak** [comment]
> I'm trying to do a pip install . This is not on anaconda . It is for Python 3.7 

pip install nupic.cpp is not supported yet, python setup.py install is. 
Can you post the command you use to install and the output setup.py should print?

**Comment by bhargav-95** [comment]
I navigate to the directory where setup.py is located.
Then , type this command..

python setup.py install

**Comment by bhargav-95** [comment]
python setup.py install --user --force

This is how i try to install (pretty basic) from the root directory of the folder

**Comment by breznak** [comment]
ok, that seems correct. 

>  and the output setup.py should print?

**Comment by bhargav-95** [comment]
It should say nupic-cpp is successfully installed.

But I get the following error.

python setup.py install

**setup.py: Calling C:\Users\I0000847\Documents\Time series Anomaly detection pack
ages\nupic.cpp-master\bindings\py\packaging\setup.py

****Traceback (most recent call last):
  File "setup.py", line 57, in <module>

  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\I0000847\Documents\Time series Anomaly detection packages\nupic
.cpp-master\bindings\py\packaging\setup.py", line 226, in <module>
    getExtensionFiles(platform)
  File "C:\Users\I0000847\Documents\Time series Anomaly detection packages\nupic
.cpp-master\bindings\py\packaging\setup.py", line 182, in getExtensionFiles
    generateExtensions()**
  File "C:\Users\I0000847\Documents\Time series Anomaly detection packages\nupic
.cpp-master\bindings\py\packaging\setup.py", line 211, in generateExtensions
    subprocess.check_call(["cmake", PY_VER, REPO_DIR])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 990, in _execute_child

    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified****

**Comment by breznak** [comment]
> C:\Users\I0000847\Documents\Time series Anomaly detection pack
ages\nupic.cpp-master\bindings\py\packaging\setup.py

can you verify the file exists actually? 
if it does, can you please try moving nupic.cpp-master to a path without spaces?

**Comment by bhargav-95** [comment]
Yes it does.
PFA screenshot.

**Comment by bhargav-95** [comment]
I renamed the path and tried ..
python setup.py install 
![github](https://user-images.githubusercontent.com/50198268/57210664-1b7a8700-6ffb-11e9-9374-8bfc60d5a436.png)

**Comment by bhargav-95** [comment]
Still the same issue

**Comment by breznak** [comment]
> Yes it does. 

no, that is the 1st one, setup.py, the other is in bindings\py\packaging\ 
...but I expect it'd exist unless you've manually deleted it

**Comment by bhargav-95** [comment]
Yes that exists
too

**Comment by bhargav-95** [comment]
![github2](https://user-images.githubusercontent.com/50198268/57211595-6c3faf00-6ffe-11e9-85a4-d15b42a7d785.png)

**Comment by breznak** [comment]
Can you test with #449 please? or wait once it's merged to master.

**Comment by bhargav-95** [comment]
JUst tested with #449 

....

C:\Users\I0000847\Documents\ts_ad_packages\nupic.cpp-master_new\nupic.cpp-master
>python setup.py install

setup.py: Calling C:\Users\I0000847\Documents\ts_ad_packages\nupic.cpp-master_ne
w\nupic.cpp-master\bindings\py\packaging\setup.py

Traceback (most recent call last):
  File "setup.py", line 57, in <module>

  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\I0000847\Documents\ts_ad_packages\nupic.cpp-master_new\nupic.cp
p-master\bindings\py\packaging\setup.py", line 226, in <module>
    getExtensionFiles(platform)
  File "C:\Users\I0000847\Documents\ts_ad_packages\nupic.cpp-master_new\nupic.cp
p-master\bindings\py\packaging\setup.py", line 182, in getExtensionFiles
    generateExtensions()
  File "C:\Users\I0000847\Documents\ts_ad_packages\nupic.cpp-master_new\nupic.cp
p-master\bindings\py\packaging\setup.py", line 211, in generateExtensions
    subprocess.check_call(["cmake", PY_VER, REPO_DIR])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 990, in _execute_child

    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by breznak** [comment]
> File "C:\Users\I0000847\Documents\ts_ad_packages\nupic.cpp-master_new\nupic.cp
p-master\bindings\py\packaging\setup.py", line 211, in generateExtensions
subprocess.check_call(["cmake", PY_VER, REPO_DIR])

seems setup.py (even the one in packaging/) is running. 
- [ ] do you have cmake installed? what's output of command line: cmake --version ? 
- [ ] can you edit the script to print PY_VER, REPO_DIR before the line 211?

**Comment by bhargav-95** [comment]
Nope cmake is not installed

**Comment by bhargav-95** [comment]
PY_VER  :  -DBINDING_BUILD=Python3
REPO_DIR  :  /home 
not 
/home/bindings/py/packaging/
where the other setup.py resides

**Comment by breznak** [comment]
> Nope cmake is not installed

well, if you see README, cmake is a requirement! 
Once you install it, this should run fine

**Comment by breznak** [comment]
@dkeeney to avoid problems like this, can we check in setup.py that the cmake binary exists and give a clearer error message if not?

**Comment by dkeeney** [comment]
Sounds like a reasonable thing to do.

**Comment by breznak** [comment]
We do (maybe) support anaconda python and cmake is a part of pip dependencies.
