### ISSUE TITLE
Cant't install on OSX

### ISSUE THREAD

**Issue by ayushpatidar** [htm-community/htm.core#959]
.o
[ 52%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/engine/HelloRegionTest.cpp.o
[ 53%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/engine/InputTest.cpp.o
[ 54%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/engine/LinkTest.cpp.o
[ 55%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/engine/NetworkTest.cpp.o
[ 55%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/engine/RESTapiTest.cpp.o
[ 56%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/engine/WatcherTest.cpp.o
[ 57%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/ntypes/ArrayTest.cpp.o
[ 57%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/ntypes/BasicTypeTest.cpp.o
[ 58%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/ntypes/CollectionTest.cpp.o
[ 59%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/ntypes/DimensionsTest.cpp.o
[ 59%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/ntypes/ValueTest.cpp.o
[ 60%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/os/DirectoryTest.cpp.o
[ 61%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/os/EnvTest.cpp.o
[ 62%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/os/PathTest.cpp.o
[ 62%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/os/TimerTest.cpp.o
[ 63%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/RegionTestUtilities.cpp.o
[ 64%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/DateEncoderRegionTest.cpp.o
[ 64%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/ClassifierRegionTest.cpp.o
[ 65%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/ScalarEncoderRegionTest.cpp.o
[ 66%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/RDSEEncoderRegionTest.cpp.o
[ 67%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/SPRegionTest.cpp.o
[ 67%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/TMRegionTest.cpp.o
[ 68%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/VectorFileTest.cpp.o
[ 69%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/regions/DatabaseRegionTest.cpp.o
[ 69%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/types/ExceptionTest.cpp.o
[ 70%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/types/SdrTest.cpp.o
[ 71%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/utils/GroupByTest.cpp.o
[ 72%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/utils/MovingAverageTest.cpp.o
[ 72%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/utils/RandomTest.cpp.o
[ 73%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/utils/VectorHelpersTest.cpp.o
[ 74%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/utils/SdrMetricsTest.cpp.o
[ 74%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/utils/TopologyTest.cpp.o
[ 75%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/utils/Sqlite3Test.cpp.o
[ 76%] Building CXX object src/test/CMakeFiles/unit_tests.dir/__/examples/hello/HelloSPTP.cpp.o
/Users/ayushpatidar/Desktop/MPL/htm.core/src/examples/hello/HelloSPTP.cpp:221:19: error: unused variable 'goldAn' [-Werror,-Wunused-variable]
      const float goldAn    = 0.637255f; //Note: this value is for a (randomly picked) datapoint, it does not have to improve (decrease) with better algorithms
                  ^
/Users/ayushpatidar/Desktop/MPL/htm.core/src/examples/hello/HelloSPTP.cpp:222:19: error: unused variable 'goldAnAvg' [-Werror,-Wunused-variable]
      const float goldAnAvg = 0.40804f; // ...the averaged value, on the other hand, should improve/decrease. 
                  ^
2 errors generated.
make[2]: *** [src/test/CMakeFiles/unit_tests.dir/__/examples/hello/HelloSPTP.cpp.o] Error 1
make[1]: *** [src/test/CMakeFiles/unit_tests.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 375, in <module>
    getExtensionFiles(platform, build_type)
  File "setup.py", line 240, in getExtensionFiles
    generateExtensions(platform, build_type)
  File "setup.py", line 287, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type, "--", "-j", "4"]) 
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.

Python version : 3.8.2

**Comment by klokare** [comment]
Hi @ayushpatidar , I ran into the same issue. Since it just an unused variable warning, I commented out those 2 lines in HelloSPTP.cpp and re-ran the "python setup.py install". It got all the way to building the .egg file but now complains 

Installed /Users/klokare/miniforge3/envs/htmcore/lib/python3.8/site-packages/htm.core-2.1.16-py3.8-macosx-11.0-arm64.egg
Processing dependencies for htm.core==2.1.16
Searching for htm.core==2.1.16
Reading https://pypi.org/simple/htm.core/
Couldn't find index page for 'htm.core' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for htm.core==2.1.16
error: Could not find suitable distribution for Requirement.parse('htm.core==2.1.16')

Going to try and find a solution to that.

**Comment by klokare** [comment]
Interestingly, that error did not seem to be a big deal as it already installed it. I was able to run "python setup test" and get most of the way through the tests before failing at 

```
[----------] Global test environment tear-down
[==========] 393 tests from 44 test suites ran. (16989 ms total)
[  PASSED  ] 392 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ClassifierRegionTest.asRealDecoder
```

I just tried the same installation via conda on my linux. Both pythons are at 3.8.12. I only get the error on my mac (M1 mini). I will test later on my Intel macbook pro and see if we can narrow it down to a mac or arm64 issue.
