### ISSUE TITLE
htm.corr-nspkg.pth error

### ISSUE THREAD

**Issue by suppathak** [htm-community/htm.core#980]
I need some help regarding getting rid of the error I got while installing htm package. 

```
Error processing line 1 of /opt/app-root/lib64/python3.8/site-packages/htm.core-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'
```

**Comment by ctrl-z-9000-times** [comment]
I would recommend building & installing the library from source.
The prebuilt packages are for outdated operating systems & outdated python versions.
